appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lHIQTJ8ypES+AmF2hJ9WN4LphgdsTOBFZ5dnTFCCp0yS/Or6IlXAKLineOf/xTtoG36wjCYu8+6vbfsKCudaNgKpCeGS/jYRlWlUuboyxulMyhlHt9xXYPPmU+6HSrMyf8DUiNKq/QfecYgz7Aukde8kChcjevVq6x40CwNC6w2WtK5FBwx0yB/Je4+UZiMTtlzQ10aRZN/JRrowRWnyh8CpIu5EtgvGdZO/oCBI16BgvGzLan/GH+RnZg9Wfu7uPD9imz/S81lMYt8ge0xYY3+kMrtC9lkos0ERCbvXGyU4enygpwxwcaUoT6uz8uMjPj/3vZZXcjLtl80XogLgEcGRvRTCWzykcGHdtkb/l6R7TyD8AXSQ9G+RfNwb+wGVdP+pnK1zMePfufzwbMYZDOKHa0xtYH+KYfv2e+R+eXBZj36JNvPC3haVbHe67se+E+TPVKaf7Y/bBkiHO4ZMJ0sCTVIbv38eFVZ2ljg/uieynGw2vXE1Q6rGOf0+nc1x6XwmZmJX1ptdpg2XrLafkDonbDLjBFjtxzKKzjJmuNXE99Y2rz8rTctfKfJmHMzAumAppjbUyszMQk4TP+vTxKCrKqfkxi8prqfv406YiGWgNx290s0YadQTdpNPUGg4w2t5Mipjp+wS8+Eh3B2zg6fuqxT5XW1S4sGAa6H1Trs=}
conda_forge_output_validation: true
